apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi