
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-cluster-metrics
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-metrics-reader
  apiGroup: rbac.authorization.k8s.io