---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deploy
  namespace: homework
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      initContainers:
        - name: init-web-server
          image:  busybox
          volumeMounts:
            - name:  homework-volume
              mountPath:  "/init"
          command: ["/bin/sh", "-c"]
          args:
            - wget -O /init/index.html https://freetestdata.com/wp-content/uploads/2023/03/sample_html_file.html 
      containers:
      - name:  web-server
        image:  nginx:1.20
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort:  800
        volumeMounts:
          - name: homework-volume
            mountPath: "/homework"
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: homework-volume
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-conf
      nodeSelector:
        homework: "true"
      restartPolicy: Always
...