---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-myapp
  namespace: homework
  labels:
    app: myapp
spec:
  storageClassName: "my-storageclass"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
...