---
apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  namespace: homework
spec:
  volumes:
    - name: homework-volume
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-conf
        items:
          - key: default.conf
            path: default.conf

  initContainers:
    - name: init-web-server
      image: busybox
      volumeMounts:
        - name: homework-volume
          mountPath: "/init"
      command: ["/bin/sh", "-c"]
      args:
        - wget -O /init/index.html https://freetestdata.com/wp-content/uploads/2023/03/sample_html_file.html

  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: homework-volume
          mountPath: "/homework"
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
      ports:
        - containerPort: 8000
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]
  
  restartPolicy: OnFailure
...
